config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'what-is-storyhoot', to: 'static_pages#about', :as => :about
  get 'privacy', to: 'static_pages#privacy', :as => :privacy
  get 'terms', to: 'static_pages#terms', :as => :terms

  resources :users, path: '/u' do
    member do
      get :subscribers
      get :activate
    end
  end
  post 'users/change_password'
  post 'users/change_username'
  get 'feed', to: 'users#newsfeed'
  get 'find', to: 'users#find_authors', :as => :find_authors
  get 'complete-facebook-sign-up', to: 'users#complete_facebook_sign_up', :as => :complete_facebook_sign_up
  post 'users/verify_account'

  resources :sessions, only: [:create, :destroy]
  get 'login', to: 'sessions#new', :as => :login
  post 'logout', to: 'sessions#destroy', :as => :logout

  resources :password_resets
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :books, path: '/story/' do
    member do
      put "like", to: 'books#like'
      put "unlike", to: 'books#unlike'
    end
  end
  get 'gif-maker-pictures', to: 'books#gif_maker_pictures', :as => :gif_maker_pictures
  get 'gif-maker-video', to: 'books#gif_maker_video', :as => :gif_maker_video
  get 'gif-upload', to: 'books#gif_upload', :as => :gif_upload
  get 'discover', to: 'books#discover', :as => :discover

  resources :categories, only: [:index, :show]
  resources :subscriptions
  resources :comments, only: [:new, :create, :destroy]
  resources :hashtags, only: [:index]

  resources :bulletins, only: [:index]
  get 'notifications', to: 'bulletins#index'

  resources :support_tickets, only: [:new, :create]
  get 'contact', to: 'support_tickets#new', :as => :contact

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title %></title>

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="Share your story with the world">

    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-64807190-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>

  <body>
    <header id="topbar">
      <div class="show-for-large-up">
        <%= render 'shared/navbar' %>
      </div>
      <div class="hide-for-large-up">
        <%= render 'shared/navbar_mobile' %>
      </div>
    </header>
    <main>
      <%= render 'shared/notices' %>
      <%= yield %>
      <%= render 'shared/footer' %>
      <div class='hide-for-medium-up'>
        <%= render 'shared/bottom_navbar' %>
      </div>
    </main>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/gif_maker.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title %></title>

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="Share your story with the world">

    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
  </head>

  <body id="gif-maker-body">
    <header id="topbar">
      <div class="show-for-large-up">
        <%= render 'shared/navbar' %>
      </div>
      <div class="hide-for-large-up">
        <%= render 'shared/navbar_mobile' %>
      </div>
    </header>
    <main>
      <%= render 'shared/notices' %>
      <%= yield %>
      <div id="loading-indicator" class="text-center">
        <%= image_tag 'loading.gif', width: '30' %>
      </div>
      <div class='hide-for-medium-up'>
        <%= render 'shared/bottom_navbar' %>
      </div>
    </main>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Welcome to Storyhoot</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/notices' %>
    <div class="landing-template">
      <%= yield %>
    </div>
    <% unless current_user %>
      <footer class="landing-footer text-center">
        <%= link_to 'Jobs', '#' %>
        <%= link_to 'Support', support_path %>
        <%= link_to 'Privacy', '#' %>
        <%= link_to 'Terms', '#' %>
      </footer>
    <% end %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/mailor.html.erb
<%= yield %>

app/views/layouts/plain.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Storyhoot! Share your story with the world</title>

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="Share your story with the world">

    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-64807190-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>

  <body>
    <%= render 'shared/notices' %>
    <div class="page-plain">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Storyhoot! Share your story with the world</title>

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="Share your story with the world">

    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-64807190-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>

  <body>
    <%= render 'shared/notices' %>

    <div class="page-splash">
      <div class="splash-background"></div>
      <div class="splash-section">
        <div class="splash-inner-section text-center">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>